In [2]:
import numpy as np

In [3]:
a= np.array([[10, 15]])
b = np.array([[20,9]])
print(a)
print(b)
a+b

[[10 15]]
[[20  9]]


array([[30, 24]])

In [8]:
#Dot products for vectors
u = np.array([10, 20])
v = np.array([25, 6])
np.dot(u,v)

370

In [10]:
#matrix and vector multiplication
a = [[5,10],[15,20]]
b = [10, 12]
np.dot(a,b)

array([170, 390])